### PR TITLE
Seeder fix housekeeping

### PR DESCRIPTION
**Pull request by dwille**

### CODE REVIEW

**Comment by asiera** [comment]
Does this happen to include the changes that Yayun has proposed in the other open pull request?

**Comment by dwille** [comment]
I don't think so. Merge hers in first, and then see how much mine can fall into place.

**Comment by asiera** [comment]
Hers is pointing to master branch, so it will take some effort to make the changes. I'll try to get to it soon.

**Comment by dwille** [comment]
Can you repoint it to devel? No sense in pointing to master until all the changes are in

**Comment by asiera** [comment]
Apparently I cannot (though everyone in the world wants this feature): https://github.com/isaacs/github/issues/18

I'll have to ask Yayun to resubmit the pull request on devel.

**Pull request merged**
